package runtoolkit.datalib.datapack;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.WorldSavePath;
import runtoolkit.datalib.core.DataLibCore;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates datapacks at runtime via the mod's GUI.
 * Uses script-based generation so that:
 *   1) The datapack can be updated without updating the mod.
 *   2) No questions arise when merging into the main account.
 */
public class DatapackGenerator {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    /**
     * Creates a new datapack in the world's datapacks directory.
     * @param server The Minecraft server instance
     * @param packName The datapack name (namespace)
     * @param description Description of the datapack
     * @param progressCallback Called with progress 0.0 to 1.0
     * @return true if successful
     */
    public static boolean createDatapack(MinecraftServer server, String packName, String description,
                                          ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        try {
            progressCallback.onProgress(0.0f, "Creating directory structure...");

            // Create pack directory
            Files.createDirectories(packDir);

            progressCallback.onProgress(0.15f, "Writing pack.mcmeta...");

            // Create pack.mcmeta (pack_format 61 for 1.21.8)
            JsonObject mcmeta = new JsonObject();
            JsonObject pack = new JsonObject();
            pack.addProperty("description", description);
            pack.addProperty("pack_format", 61);
            mcmeta.add("pack", pack);
            Files.writeString(packDir.resolve("pack.mcmeta"), GSON.toJson(mcmeta));

            progressCallback.onProgress(0.3f, "Creating namespace directories...");

            // Create data/<namespace> structure
            Path dataDir = packDir.resolve("data").resolve(packName);
            Files.createDirectories(dataDir.resolve("function"));
            Files.createDirectories(dataDir.resolve("tags").resolve("function"));

            progressCallback.onProgress(0.5f, "Generating init function...");

            // Create init.mcfunction
            String initContent = """
                    # %s - Init function
                    # Generated by DataLib Engine
                    
                    tellraw @a {"text":"[%s] Loaded!","color":"green"}
                    """.formatted(packName, packName);
            Files.writeString(dataDir.resolve("function").resolve("init.mcfunction"), initContent);

            progressCallback.onProgress(0.65f, "Creating tick function...");

            // Create tick.mcfunction (empty placeholder)
            Files.writeString(dataDir.resolve("function").resolve("tick.mcfunction"),
                    "# %s - Tick function\n# Generated by DataLib Engine\n".formatted(packName));

            progressCallback.onProgress(0.8f, "Setting up function tags...");

            // Create load function tag
            JsonObject loadTag = new JsonObject();
            JsonArray loadValues = new JsonArray();
            loadValues.add(packName + ":init");
            loadTag.add("values", loadValues);
            Path minecraftTags = packDir.resolve("data").resolve("minecraft").resolve("tags").resolve("function");
            Files.createDirectories(minecraftTags);
            Files.writeString(minecraftTags.resolve("load.json"), GSON.toJson(loadTag));

            // Create tick function tag
            JsonObject tickTag = new JsonObject();
            JsonArray tickValues = new JsonArray();
            tickValues.add(packName + ":tick");
            tickTag.add("values", tickValues);
            Files.writeString(minecraftTags.resolve("tick.json"), GSON.toJson(tickTag));

            progressCallback.onProgress(0.9f, "Adding DataLib marker...");

            // Add managed marker
            Files.writeString(packDir.resolve(".datalib_managed"), "managed_by=datalib\nversion=6.0.0\n");

            progressCallback.onProgress(1.0f, "Datapack created successfully!");

            DataLibCore.LOGGER.info("[DataLib] Datapack '{}' created at {}", packName, packDir);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to create datapack '{}'", packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Adds dataLib dependency to an existing datapack.
     * Injects the datalib:engine global{loaded:1b} check and check_all function reference.
     */
    public static boolean addDataLibDependency(MinecraftServer server, String packName,
                                                ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        if (!Files.exists(packDir)) {
            progressCallback.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            progressCallback.onProgress(0.0f, "Analyzing datapack structure...");

            Path dataDir = packDir.resolve("data").resolve(packName);
            Files.createDirectories(dataDir.resolve("function"));

            progressCallback.onProgress(0.2f, "Creating dependency check function...");

            // Create datalib_check.mcfunction
            String checkContent = """
                    # DataLib Dependency Check
                    # Generated by DataLib Engine
                    # Checks datalib:engine global{loaded:1b}
                    
                    execute store result score #datalib_loaded datalib.temp run data get storage datalib:engine loaded
                    execute if score #datalib_loaded datalib.temp matches 1 run function %s:init
                    execute unless score #datalib_loaded datalib.temp matches 1 run tellraw @a {"text":"[%s] Error: DataLib engine not loaded!","color":"red"}
                    """.formatted(packName, packName);
            Files.writeString(dataDir.resolve("function").resolve("datalib_check.mcfunction"), checkContent);

            progressCallback.onProgress(0.4f, "Creating datalib_setup function...");

            // Create datalib_setup.mcfunction
            String setupContent = """
                    # DataLib Setup
                    # Generated by DataLib Engine
                    # Sets up dataLib integration
                    
                    # Verify dataLib engine is loaded
                    data modify storage datalib:engine loaded set value 1b
                    
                    # Register with check_all
                    tellraw @a {"text":"[%s] DataLib dependency loaded.","color":"aqua"}
                    
                    # Run init
                    function %s:init
                    """.formatted(packName, packName);
            Files.writeString(dataDir.resolve("function").resolve("datalib_setup.mcfunction"), setupContent);

            progressCallback.onProgress(0.6f, "Updating load tag...");

            // Update load function tag to use datalib_check instead of direct init
            Path minecraftTags = packDir.resolve("data").resolve("minecraft").resolve("tags").resolve("function");
            Files.createDirectories(minecraftTags);

            JsonObject loadTag = new JsonObject();
            JsonArray loadValues = new JsonArray();
            loadValues.add(packName + ":datalib_check");
            loadTag.add("values", loadValues);
            Files.writeString(minecraftTags.resolve("load.json"), GSON.toJson(loadTag));

            progressCallback.onProgress(0.8f, "Adding dataLib check_all reference...");

            // Create datalib tag reference
            Path datalibTags = packDir.resolve("data").resolve("datalib").resolve("tags").resolve("function");
            Files.createDirectories(datalibTags);

            JsonObject checkAllTag = new JsonObject();
            JsonArray checkAllValues = new JsonArray();
            checkAllValues.add(packName + ":datalib_check");
            checkAllTag.add("values", checkAllValues);
            Files.writeString(datalibTags.resolve("check_all.json"), GSON.toJson(checkAllTag));

            progressCallback.onProgress(0.95f, "Updating marker...");

            // Update marker
            Path marker = packDir.resolve(".datalib_managed");
            String markerContent = Files.exists(marker) ? Files.readString(marker) : "";
            if (!markerContent.contains("datalib_dependency")) {
                markerContent += "\ndatalib_dependency=true\n";
                Files.writeString(marker, markerContent);
            }

            progressCallback.onProgress(1.0f, "DataLib dependency added successfully!");

            DataLibCore.LOGGER.info("[DataLib] Dependency added to '{}'", packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to add dependency to '{}'", packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Adds a module (mcfunction file) to an existing datapack.
     */
    public static boolean addModule(MinecraftServer server, String packName, String moduleName,
                                     String moduleContent, ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        if (!Files.exists(packDir)) {
            progressCallback.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            progressCallback.onProgress(0.0f, "Preparing module...");

            Path funcDir = packDir.resolve("data").resolve(packName).resolve("function");
            Files.createDirectories(funcDir);

            progressCallback.onProgress(0.3f, "Writing function file...");

            // Handle subdirectories in module name (e.g., "combat/attack")
            String fileName = moduleName.replace("/", java.io.File.separator) + ".mcfunction";
            Path funcFile = funcDir.resolve(fileName);
            Files.createDirectories(funcFile.getParent());

            String header = """
                    # Module: %s
                    # Datapack: %s
                    # Generated by DataLib Engine
                    
                    """.formatted(moduleName, packName);
            Files.writeString(funcFile, header + moduleContent);

            progressCallback.onProgress(0.7f, "Validating module...");

            // Basic validation
            if (moduleContent.isBlank()) {
                DataLibCore.LOGGER.warn("[DataLib] Module '{}' in '{}' is empty.", moduleName, packName);
            }

            progressCallback.onProgress(1.0f, "Module '" + moduleName + "' added successfully!");

            DataLibCore.LOGGER.info("[DataLib] Module '{}' added to '{}'", moduleName, packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to add module '{}' to '{}'", moduleName, packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Removes a module from a datapack.
     */
    public static boolean removeModule(MinecraftServer server, String packName, String moduleName,
                                        ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        if (!Files.exists(packDir)) {
            progressCallback.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            progressCallback.onProgress(0.0f, "Locating module...");

            Path funcFile = packDir.resolve("data").resolve(packName).resolve("function")
                    .resolve(moduleName.replace("/", java.io.File.separator) + ".mcfunction");

            if (!Files.exists(funcFile)) {
                progressCallback.onProgress(-1.0f, "Module not found: " + moduleName);
                return false;
            }

            progressCallback.onProgress(0.5f, "Deleting module...");
            Files.delete(funcFile);

            // Clean empty parent directories
            Path parent = funcFile.getParent();
            Path funcDir = packDir.resolve("data").resolve(packName).resolve("function");
            while (!parent.equals(funcDir)) {
                try (var entries = Files.list(parent)) {
                    if (entries.findFirst().isEmpty()) {
                        Files.delete(parent);
                        parent = parent.getParent();
                    } else {
                        break;
                    }
                }
            }

            progressCallback.onProgress(1.0f, "Module '" + moduleName + "' removed.");

            DataLibCore.LOGGER.info("[DataLib] Module '{}' removed from '{}'", moduleName, packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to remove module '{}' from '{}'", moduleName, packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Edits/updates a module in a datapack.
     */
    public static boolean editModule(MinecraftServer server, String packName, String moduleName,
                                      String newContent, ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        if (!Files.exists(packDir)) {
            progressCallback.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            progressCallback.onProgress(0.0f, "Locating module...");

            Path funcFile = packDir.resolve("data").resolve(packName).resolve("function")
                    .resolve(moduleName.replace("/", java.io.File.separator) + ".mcfunction");

            if (!Files.exists(funcFile)) {
                progressCallback.onProgress(-1.0f, "Module not found: " + moduleName);
                return false;
            }

            progressCallback.onProgress(0.4f, "Updating content...");

            String header = """
                    # Module: %s
                    # Datapack: %s
                    # Updated by DataLib Engine
                    
                    """.formatted(moduleName, packName);
            Files.writeString(funcFile, header + newContent);

            progressCallback.onProgress(1.0f, "Module '" + moduleName + "' updated.");

            DataLibCore.LOGGER.info("[DataLib] Module '{}' updated in '{}'", moduleName, packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to edit module '{}' in '{}'", moduleName, packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Removes dataLib dependency from a datapack.
     */
    public static boolean removeDataLibDependency(MinecraftServer server, String packName,
                                                   ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        if (!Files.exists(packDir)) {
            progressCallback.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            progressCallback.onProgress(0.0f, "Removing dependency files...");

            Path dataDir = packDir.resolve("data").resolve(packName).resolve("function");

            // Delete datalib_check.mcfunction
            Path checkFile = dataDir.resolve("datalib_check.mcfunction");
            if (Files.exists(checkFile)) Files.delete(checkFile);

            progressCallback.onProgress(0.3f, "Removing setup function...");

            // Delete datalib_setup.mcfunction
            Path setupFile = dataDir.resolve("datalib_setup.mcfunction");
            if (Files.exists(setupFile)) Files.delete(setupFile);

            progressCallback.onProgress(0.5f, "Removing datalib tags...");

            // Remove datalib tags directory
            Path datalibTags = packDir.resolve("data").resolve("datalib");
            if (Files.exists(datalibTags)) {
                deleteDirectory(datalibTags);
            }

            progressCallback.onProgress(0.7f, "Restoring load tag...");

            // Restore load tag to point to init
            Path minecraftTags = packDir.resolve("data").resolve("minecraft").resolve("tags").resolve("function");
            if (Files.exists(minecraftTags.resolve("load.json"))) {
                JsonObject loadTag = new JsonObject();
                JsonArray loadValues = new JsonArray();
                loadValues.add(packName + ":init");
                loadTag.add("values", loadValues);
                Files.writeString(minecraftTags.resolve("load.json"), GSON.toJson(loadTag));
            }

            progressCallback.onProgress(0.9f, "Updating marker...");

            Path marker = packDir.resolve(".datalib_managed");
            if (Files.exists(marker)) {
                String content = Files.readString(marker);
                content = content.replace("datalib_dependency=true", "datalib_dependency=false");
                Files.writeString(marker, content);
            }

            progressCallback.onProgress(1.0f, "DataLib dependency removed.");

            DataLibCore.LOGGER.info("[DataLib] Dependency removed from '{}'", packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to remove dependency from '{}'", packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Deletes an entire datapack.
     */
    public static boolean deleteDatapack(MinecraftServer server, String packName,
                                          ProgressCallback progressCallback) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path packDir = datapacksDir.resolve(packName);

        if (!Files.exists(packDir)) {
            progressCallback.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            progressCallback.onProgress(0.0f, "Deleting datapack...");
            progressCallback.onProgress(0.3f, "Removing files...");

            deleteDirectory(packDir);

            progressCallback.onProgress(1.0f, "Datapack '" + packName + "' deleted.");

            DataLibCore.LOGGER.info("[DataLib] Datapack '{}' deleted", packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to delete datapack '{}'", packName, e);
            progressCallback.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    /**
     * Lists all modules (mcfunction files) in a datapack.
     */
    public static List<String> listModules(MinecraftServer server, String packName) {
        List<String> modules = new ArrayList<>();
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path funcDir = datapacksDir.resolve(packName).resolve("data").resolve(packName).resolve("function");

        if (!Files.exists(funcDir)) return modules;

        try (var walk = Files.walk(funcDir)) {
            walk.filter(p -> p.toString().endsWith(".mcfunction"))
                .forEach(p -> {
                    String relative = funcDir.relativize(p).toString();
                    // Remove .mcfunction extension and normalize separators
                    relative = relative.replace(".mcfunction", "").replace(java.io.File.separator, "/");
                    modules.add(relative);
                });
        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to list modules for '{}'", packName, e);
        }

        return modules;
    }

    /**
     * Lists all datapacks in the world (both managed and unmanaged).
     */
    public static List<DatapackInfo> listDatapacks(MinecraftServer server) {
        List<DatapackInfo> packs = new ArrayList<>();
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);

        if (!Files.exists(datapacksDir)) return packs;

        try (var stream = Files.list(datapacksDir)) {
            stream.filter(Files::isDirectory).forEach(dir -> {
                String name = dir.getFileName().toString();
                boolean managed = Files.exists(dir.resolve(".datalib_managed"));
                boolean hasDependency = false;
                if (managed) {
                    try {
                        String marker = Files.readString(dir.resolve(".datalib_managed"));
                        hasDependency = marker.contains("datalib_dependency=true");
                    } catch (IOException ignored) {}
                }
                packs.add(new DatapackInfo(name, managed, hasDependency));
            });
        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to list datapacks", e);
        }

        return packs;
    }

    /**
     * Reads the content of a module.
     */
    public static String readModule(MinecraftServer server, String packName, String moduleName) {
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);
        Path funcFile = datapacksDir.resolve(packName).resolve("data").resolve(packName)
                .resolve("function").resolve(moduleName.replace("/", java.io.File.separator) + ".mcfunction");

        if (!Files.exists(funcFile)) return null;

        try {
            return Files.readString(funcFile);
        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to read module '{}'", moduleName, e);
            return null;
        }
    }

    private static void deleteDirectory(Path dir) throws IOException {
        if (!Files.exists(dir)) return;
        try (var walk = Files.walk(dir)) {
            walk.sorted(java.util.Comparator.reverseOrder())
                .forEach(p -> {
                    try { Files.delete(p); } catch (IOException ignored) {}
                });
        }
    }

    public record DatapackInfo(String name, boolean managed, boolean hasDataLibDependency) {}

    @FunctionalInterface
    public interface ProgressCallback {
        void onProgress(float progress, String message);
    }
}
