package runtoolkit.datalib.datapack;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.WorldSavePath;
import runtoolkit.datalib.core.DataLibCore;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Generates and manages datapacks at runtime via the mod's GUI.
 *
 * Uses script-based generation so that:
 *   1) Datapacks can be updated without updating the mod.
 *   2) No questions arise when merging into the main account.
 *
 * Generated packs follow the real dataLib conventions:
 *   - Lantern Load integration via data/load/tags/function/load.json
 *   - datalib:engine global{loaded:1b} check for dependency
 *   - #datalib:init tag registration for dependent packs
 *   - pack_format 61 for 1.21.8
 *   - supported_formats range for multi-version compat
 */
public class DatapackGenerator {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    // ───────────────────────── CREATE DATAPACK ─────────────────────────

    public static boolean createDatapack(MinecraftServer server, String packName, String description,
                                          ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        try {
            cb.onProgress(0.0f, "Creating directory structure...");
            Files.createDirectories(packDir);

            cb.onProgress(0.15f, "Writing pack.mcmeta...");
            writeMcmeta(packDir, description);

            cb.onProgress(0.30f, "Creating namespace directories...");
            Path funcDir = packDir.resolve("data").resolve(packName).resolve("function");
            Files.createDirectories(funcDir);

            cb.onProgress(0.45f, "Generating load function...");
            String loadFn = """
                    # %s — load
                    # Called on world load / /reload via #minecraft:load
                    # Generated by DataLib Mod
                    
                    tellraw @a[permission_level=2] {"text":"[%s] ","color":"aqua","extra":[{"text":"Loaded.","color":"green"}]}
                    """.formatted(packName, packName);
            Files.writeString(funcDir.resolve("load.mcfunction"), loadFn);

            cb.onProgress(0.55f, "Generating tick function...");
            String tickFn = """
                    # %s — tick
                    # Called every game tick via #minecraft:tick
                    # Generated by DataLib Mod
                    """.formatted(packName);
            Files.writeString(funcDir.resolve("tick.mcfunction"), tickFn);

            cb.onProgress(0.70f, "Setting up function tags...");
            // minecraft:load → <pack>:load
            writeTag(packDir, "minecraft", "load", packName + ":load", false);
            // minecraft:tick → <pack>:tick
            writeTag(packDir, "minecraft", "tick", packName + ":tick", false);

            cb.onProgress(0.85f, "Adding DataLib marker...");
            Files.writeString(packDir.resolve(".datalib_managed"),
                    "managed_by=datalib-mod\npack_format=61\ndatalib_dependency=false\n");

            cb.onProgress(1.0f, "Datapack '" + packName + "' created!");

            DataLibCore.LOGGER.info("[DataLib] Datapack '{}' created at {}", packName, packDir);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to create datapack '{}'", packName, e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ────────────────────── ADD DATALIB DEPENDENCY ──────────────────────

    /**
     * Adds dataLib dependency to an existing datapack:
     *   1. Creates a datalib_check.mcfunction that verifies
     *      datalib:engine global{loaded:1b} before calling the pack's load.
     *   2. Registers the pack in #datalib:init so the datapack engine
     *      knows about it on load.
     *   3. Updates the minecraft:load tag to go through the check first.
     */
    public static boolean addDataLibDependency(MinecraftServer server, String packName,
                                                ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        if (!Files.exists(packDir)) {
            cb.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            cb.onProgress(0.0f, "Analyzing datapack structure...");

            Path funcDir = packDir.resolve("data").resolve(packName).resolve("function");
            Files.createDirectories(funcDir);

            cb.onProgress(0.15f, "Creating datalib_check function...");

            // datalib_check verifies the engine is loaded, then calls load
            String checkFn = """
                    # %s — DataLib dependency check
                    # Verifies datalib:engine global{loaded:1b} before loading.
                    # Generated by DataLib Mod
                    
                    # Guard: dataLib engine must be loaded
                    execute unless data storage datalib:engine global{loaded:1b} run return run tellraw @a[permission_level=2] {"text":"[%s] ","color":"red","extra":[{"text":"dataLib engine not loaded! Skipping init.","color":"white"}]}
                    
                    # Engine is loaded — proceed
                    function %s:load
                    """.formatted(packName, packName, packName);
            Files.writeString(funcDir.resolve("datalib_check.mcfunction"), checkFn);

            cb.onProgress(0.35f, "Creating datalib_setup function...");

            // datalib_setup — called from #datalib:init during engine load
            String setupFn = """
                    # %s — DataLib setup
                    # Called by #datalib:init when the dataLib engine loads.
                    # Generated by DataLib Mod
                    
                    tellraw @a[permission_level=2] {"text":"[%s] ","color":"aqua","extra":[{"text":"DataLib dependency registered.","color":"white"}]}
                    
                    # Run the pack's own load function
                    function %s:load
                    """.formatted(packName, packName, packName);
            Files.writeString(funcDir.resolve("datalib_setup.mcfunction"), setupFn);

            cb.onProgress(0.50f, "Updating load tag...");

            // Change minecraft:load to call datalib_check instead of load directly
            writeTag(packDir, "minecraft", "load", packName + ":datalib_check", true);

            cb.onProgress(0.65f, "Registering in #datalib:init tag...");

            // Register in datalib:init function tag
            // This lives in the pack's own data/datalib/tags/function/init.json
            Path datalibInitTag = packDir.resolve("data").resolve("datalib")
                    .resolve("tags").resolve("function");
            Files.createDirectories(datalibInitTag);

            JsonObject initTag = new JsonObject();
            initTag.addProperty("replace", false);
            JsonArray vals = new JsonArray();
            vals.add(packName + ":datalib_setup");
            initTag.add("values", vals);
            Files.writeString(datalibInitTag.resolve("init.json"), GSON.toJson(initTag));

            cb.onProgress(0.80f, "Registering in #datalib:events/on_load tag...");

            // Also register in events/on_load for full lifecycle integration
            Path eventsTag = packDir.resolve("data").resolve("datalib")
                    .resolve("tags").resolve("function").resolve("events");
            Files.createDirectories(eventsTag);

            JsonObject onLoadTag = new JsonObject();
            onLoadTag.addProperty("replace", false);
            JsonArray onLoadVals = new JsonArray();
            onLoadVals.add(packName + ":datalib_setup");
            onLoadTag.add("values", onLoadVals);
            Files.writeString(eventsTag.resolve("on_load.json"), GSON.toJson(onLoadTag));

            cb.onProgress(0.90f, "Updating marker...");

            Path marker = packDir.resolve(".datalib_managed");
            String markerContent = Files.exists(marker) ? Files.readString(marker) : "managed_by=datalib-mod\n";
            markerContent = markerContent.replace("datalib_dependency=false", "");
            if (!markerContent.contains("datalib_dependency=true")) {
                markerContent += "datalib_dependency=true\n";
            }
            Files.writeString(marker, markerContent);

            cb.onProgress(1.0f, "DataLib dependency added to '" + packName + "'!");

            DataLibCore.LOGGER.info("[DataLib] Dependency added to '{}'", packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to add dependency to '{}'", packName, e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ────────────────────── ADD MODULE / MCFUNCTION ──────────────────────

    public static boolean addModule(MinecraftServer server, String packName, String moduleName,
                                     String moduleContent, ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        if (!Files.exists(packDir)) {
            cb.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            cb.onProgress(0.0f, "Preparing module...");

            Path funcDir = packDir.resolve("data").resolve(packName).resolve("function");
            Files.createDirectories(funcDir);

            cb.onProgress(0.25f, "Writing function file...");

            // Support subdirectories in module name (e.g., "combat/attack")
            String fileName = moduleName.replace("/", java.io.File.separator) + ".mcfunction";
            Path funcFile = funcDir.resolve(fileName);
            Files.createDirectories(funcFile.getParent());

            String header = """
                    # Module: %s
                    # Datapack: %s
                    # Generated by DataLib Mod
                    
                    """.formatted(moduleName, packName);
            Files.writeString(funcFile, header + moduleContent);

            cb.onProgress(0.75f, "Validating...");

            if (moduleContent.isBlank()) {
                DataLibCore.LOGGER.warn("[DataLib] Module '{}' in '{}' is empty.", moduleName, packName);
            }

            cb.onProgress(1.0f, "Module '" + moduleName + "' added!");

            DataLibCore.LOGGER.info("[DataLib] Module '{}' added to '{}'", moduleName, packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to add module '{}' to '{}'", moduleName, packName, e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ────────────────────── REMOVE MODULE ──────────────────────

    public static boolean removeModule(MinecraftServer server, String packName, String moduleName,
                                        ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        if (!Files.exists(packDir)) {
            cb.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            cb.onProgress(0.0f, "Locating module...");

            Path funcFile = packDir.resolve("data").resolve(packName).resolve("function")
                    .resolve(moduleName.replace("/", java.io.File.separator) + ".mcfunction");

            if (!Files.exists(funcFile)) {
                cb.onProgress(-1.0f, "Module not found: " + moduleName);
                return false;
            }

            cb.onProgress(0.40f, "Deleting module...");
            Files.delete(funcFile);

            // Clean empty parent directories up to the function/ dir
            Path parent = funcFile.getParent();
            Path funcRoot = packDir.resolve("data").resolve(packName).resolve("function");
            while (!parent.equals(funcRoot)) {
                try (var entries = Files.list(parent)) {
                    if (entries.findFirst().isEmpty()) {
                        Files.delete(parent);
                        parent = parent.getParent();
                    } else break;
                }
            }

            cb.onProgress(1.0f, "Module '" + moduleName + "' removed.");

            DataLibCore.LOGGER.info("[DataLib] Module '{}' removed from '{}'", moduleName, packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to remove module", e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ────────────────────── EDIT MODULE ──────────────────────

    public static boolean editModule(MinecraftServer server, String packName, String moduleName,
                                      String newContent, ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        if (!Files.exists(packDir)) {
            cb.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            cb.onProgress(0.0f, "Locating module...");

            Path funcFile = packDir.resolve("data").resolve(packName).resolve("function")
                    .resolve(moduleName.replace("/", java.io.File.separator) + ".mcfunction");

            if (!Files.exists(funcFile)) {
                cb.onProgress(-1.0f, "Module not found: " + moduleName);
                return false;
            }

            cb.onProgress(0.40f, "Updating content...");

            String header = """
                    # Module: %s
                    # Datapack: %s
                    # Updated by DataLib Mod
                    
                    """.formatted(moduleName, packName);
            Files.writeString(funcFile, header + newContent);

            cb.onProgress(1.0f, "Module '" + moduleName + "' updated.");

            DataLibCore.LOGGER.info("[DataLib] Module '{}' updated in '{}'", moduleName, packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to edit module", e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ──────────────────── REMOVE DEPENDENCY ────────────────────

    public static boolean removeDataLibDependency(MinecraftServer server, String packName,
                                                   ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        if (!Files.exists(packDir)) {
            cb.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            cb.onProgress(0.0f, "Removing dependency files...");

            Path funcDir = packDir.resolve("data").resolve(packName).resolve("function");

            deleteIfExists(funcDir.resolve("datalib_check.mcfunction"));

            cb.onProgress(0.20f, "Removing setup function...");
            deleteIfExists(funcDir.resolve("datalib_setup.mcfunction"));

            cb.onProgress(0.40f, "Removing datalib tags...");
            Path datalibData = packDir.resolve("data").resolve("datalib");
            if (Files.exists(datalibData)) {
                deleteDirectory(datalibData);
            }

            cb.onProgress(0.60f, "Restoring load tag...");
            // Point minecraft:load back to <pack>:load
            writeTag(packDir, "minecraft", "load", packName + ":load", true);

            cb.onProgress(0.85f, "Updating marker...");
            Path marker = packDir.resolve(".datalib_managed");
            if (Files.exists(marker)) {
                String content = Files.readString(marker)
                        .replace("datalib_dependency=true", "datalib_dependency=false");
                Files.writeString(marker, content);
            }

            cb.onProgress(1.0f, "DataLib dependency removed from '" + packName + "'.");

            DataLibCore.LOGGER.info("[DataLib] Dependency removed from '{}'", packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to remove dependency", e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ────────────────────── DELETE DATAPACK ──────────────────────

    public static boolean deleteDatapack(MinecraftServer server, String packName,
                                          ProgressCallback cb) {
        Path packDir = server.getSavePath(WorldSavePath.DATAPACKS).resolve(packName);

        if (!Files.exists(packDir)) {
            cb.onProgress(-1.0f, "Datapack not found: " + packName);
            return false;
        }

        try {
            cb.onProgress(0.0f, "Deleting datapack...");
            cb.onProgress(0.30f, "Removing files...");

            deleteDirectory(packDir);

            cb.onProgress(1.0f, "Datapack '" + packName + "' deleted.");

            DataLibCore.LOGGER.info("[DataLib] Datapack '{}' deleted", packName);
            return true;

        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to delete datapack", e);
            cb.onProgress(-1.0f, "Error: " + e.getMessage());
            return false;
        }
    }

    // ────────────────────── LIST HELPERS ──────────────────────

    public static List<String> listModules(MinecraftServer server, String packName) {
        List<String> modules = new ArrayList<>();
        Path funcDir = server.getSavePath(WorldSavePath.DATAPACKS)
                .resolve(packName).resolve("data").resolve(packName).resolve("function");

        if (!Files.exists(funcDir)) return modules;

        try (var walk = Files.walk(funcDir)) {
            walk.filter(p -> p.toString().endsWith(".mcfunction"))
                .forEach(p -> {
                    String rel = funcDir.relativize(p).toString();
                    rel = rel.replace(".mcfunction", "").replace(java.io.File.separator, "/");
                    modules.add(rel);
                });
        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to list modules for '{}'", packName, e);
        }

        return modules;
    }

    public static List<DatapackInfo> listDatapacks(MinecraftServer server) {
        List<DatapackInfo> packs = new ArrayList<>();
        Path datapacksDir = server.getSavePath(WorldSavePath.DATAPACKS);

        if (!Files.exists(datapacksDir)) return packs;

        try (var stream = Files.list(datapacksDir)) {
            stream.filter(Files::isDirectory).forEach(dir -> {
                String name = dir.getFileName().toString();
                boolean managed = Files.exists(dir.resolve(".datalib_managed"));
                boolean hasDep = false;
                if (managed) {
                    try {
                        String m = Files.readString(dir.resolve(".datalib_managed"));
                        hasDep = m.contains("datalib_dependency=true");
                    } catch (IOException ignored) {}
                }
                packs.add(new DatapackInfo(name, managed, hasDep));
            });
        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to list datapacks", e);
        }

        return packs;
    }

    public static String readModule(MinecraftServer server, String packName, String moduleName) {
        Path funcFile = server.getSavePath(WorldSavePath.DATAPACKS)
                .resolve(packName).resolve("data").resolve(packName)
                .resolve("function")
                .resolve(moduleName.replace("/", java.io.File.separator) + ".mcfunction");

        if (!Files.exists(funcFile)) return null;

        try {
            return Files.readString(funcFile);
        } catch (IOException e) {
            DataLibCore.LOGGER.error("[DataLib] Failed to read module '{}'", moduleName, e);
            return null;
        }
    }

    // ────────────────────── INTERNAL HELPERS ──────────────────────

    private static void writeMcmeta(Path packDir, String description) throws IOException {
        JsonObject mcmeta = new JsonObject();
        JsonObject pack = new JsonObject();
        pack.addProperty("pack_format", 61);

        // description as JSON text component (like the real dataLib)
        JsonArray desc = new JsonArray();
        JsonObject nameObj = new JsonObject();
        nameObj.addProperty("text", packDir.getFileName().toString());
        nameObj.addProperty("color", "#00ccff");
        nameObj.addProperty("bold", true);
        desc.add(nameObj);
        JsonObject descObj = new JsonObject();
        descObj.addProperty("text", " | " + description);
        descObj.addProperty("color", "#ffaa00");
        desc.add(descObj);
        pack.add("description", desc);

        // supported_formats for multi-version
        JsonObject supported = new JsonObject();
        supported.addProperty("min_inclusive", 57);
        supported.addProperty("max_inclusive", 101);
        pack.add("supported_formats", supported);

        mcmeta.add("pack", pack);
        Files.writeString(packDir.resolve("pack.mcmeta"), GSON.toJson(mcmeta));
    }

    private static void writeTag(Path packDir, String namespace, String tagName,
                                  String functionId, boolean replace) throws IOException {
        Path tagDir = packDir.resolve("data").resolve(namespace)
                .resolve("tags").resolve("function");
        Files.createDirectories(tagDir);

        JsonObject tag = new JsonObject();
        if (replace) tag.addProperty("replace", true);
        JsonArray vals = new JsonArray();
        vals.add(functionId);
        tag.add("values", vals);
        Files.writeString(tagDir.resolve(tagName + ".json"), GSON.toJson(tag));
    }

    private static void deleteIfExists(Path path) throws IOException {
        if (Files.exists(path)) Files.delete(path);
    }

    private static void deleteDirectory(Path dir) throws IOException {
        if (!Files.exists(dir)) return;
        try (var walk = Files.walk(dir)) {
            walk.sorted(Comparator.reverseOrder()).forEach(p -> {
                try { Files.delete(p); } catch (IOException ignored) {}
            });
        }
    }

    public record DatapackInfo(String name, boolean managed, boolean hasDataLibDependency) {}

    @FunctionalInterface
    public interface ProgressCallback {
        void onProgress(float progress, String message);
    }
}
